name: CI

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest wheel
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        shell: bash
      - name: Build using setup.py
        run: python setup.py sdist bdist_wheel
      - name: Test with pytest
        run: |
          pytest
      - name: Upload for release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_files
          path: dist/*
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download files
        uses: actions/download-artifact@v4.1.7
      - name: Prepare files
        run: |
          mkdir dist
          find . -type f -print
          find . -type f -name *.whl -exec cp {} dist/ \;
          find . -type f -name *.tar.gz -exec cp {} dist/ \;
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: dist/

